### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by theodorosploumis** [sciactive/logalyzer-server#1]
Hi, I would like to ask you for same basic documentation if easy. 
At least how to start using this tool, thanks!

**Comment by hperrin** [comment]
Sorry, this project uses a deprecated version of my ORM library, and I won't be maintaining it anymore. Also, sorry to answer your question almost 4 years late.

**Comment by hperrin** [comment]
To anyone interested, you can check out https://github.com/sciactive/nymphjs. It would be a hard task, but you can fork this repo and rewrite the server to use Node.js.
